import type { ToolDefinition } from "@/lib/llm";
import type { AttachmentMeta } from "@/lib/db";
import fs from "fs";
import path from "path";
import crypto from "crypto";
import { Document, Packer, Paragraph, TextRun } from "docx";
import ExcelJS from "exceljs";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { PNG } from "pngjs";
import jpeg from "jpeg-js";
import {
  FILE_IMAGE_DEFAULT_WIDTH,
  FILE_IMAGE_DEFAULT_HEIGHT,
  FILE_IMAGE_MIN_DIMENSION,
  FILE_IMAGE_MAX_DIMENSION,
} from "@/lib/constants";
import { BaseTool, type ToolExecutionContext } from "./base-tool";

const ATTACHMENTS_ROOT = path.join(process.cwd(), "data", "attachments");

export const FILE_TOOL_NAMES = {
  GENERATE: "builtin.file_generate",
} as const;

const FILE_TOOL_ALIASES = new Map<string, string>([
  ["file_generate", FILE_TOOL_NAMES.GENERATE],
]);

export const FILE_TOOLS_REQUIRING_APPROVAL: string[] = [];

export const BUILTIN_FILE_TOOLS: ToolDefinition[] = [
  {
    name: FILE_TOOL_NAMES.GENERATE,
    description:
      "Generate a file (txt, md, csv, json, docx, xlsx, pdf, png, jpg) and store it as an attachment in the current thread.",
    inputSchema: {
      type: "object",
      properties: {
        filename: { type: "string", description: "Target filename. Extension can be omitted and will be inferred from format." },
        format: {
          type: "string",
          enum: ["txt", "md", "csv", "json", "docx", "xlsx", "pdf", "png", "jpg"],
          description: "Output file format.",
        },
        content: { type: "string", description: "Main textual content used by text, markdown, docx and pdf formats." },
        jsonData: { type: "object", description: "Structured JSON object/array to serialize for json/csv/xlsx formats." },
        width: { type: "number", description: "Image width for png/jpg (default 1024)." },
        height: { type: "number", description: "Image height for png/jpg (default 576)." },
      },
      required: ["filename", "format"],
    },
  },
];

const MIME_BY_FORMAT: Record<string, string> = {
  txt: "text/plain",
  md: "text/markdown",
  csv: "text/csv",
  json: "application/json",
  docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  pdf: "application/pdf",
  png: "image/png",
  jpg: "image/jpeg",
};

function resolveFileToolName(name: string): string {
  return FILE_TOOL_ALIASES.get(name) || name;
}

function normalizePdfText(input: string): string {
  return input
    .replace(/\u2011/g, "-")
    .replace(/\u2010/g, "-")
    .replace(/\u2012|\u2013|\u2014|\u2212/g, "-")
    .replace(/[\u2018\u2019\u2032]/g, "'")
    .replace(/[\u201C\u201D\u2033]/g, '"')
    .replace(/\u2026/g, "...")
    .replace(/[\u00A0\u202F]/g, " ")
    .replace(/[^\x09\x0A\x0D\x20-\x7E\xA0-\xFF]/g, "?");
}

function sanitizeFilename(raw: string): string {
  const base = path.basename(raw).replace(/[<>:"/\\|?*\x00-\x1F]/g, "_").trim();
  return base || `file-${Date.now()}`;
}

function normalizeRows(input: unknown): Array<Record<string, unknown>> {
  if (Array.isArray(input)) {
    return input.filter((x): x is Record<string, unknown> => !!x && typeof x === "object" && !Array.isArray(x));
  }
  if (input && typeof input === "object") return [input as Record<string, unknown>];
  return [];
}

async function generateBytes(format: string, content: string, jsonData: unknown, width: number, height: number): Promise<Buffer> {
  switch (format) {
    case "txt":
    case "md":
      return Buffer.from(content || "", "utf8");

    case "json": {
      const payload = jsonData !== undefined ? jsonData : content;
      return Buffer.from(JSON.stringify(payload ?? {}, null, 2), "utf8");
    }

    case "csv": {
      const rows = normalizeRows(jsonData !== undefined ? jsonData : content ? [{ content }] : []);
      const headers = Array.from(new Set(rows.flatMap((r) => Object.keys(r))));
      const lines = [headers.join(",")];
      for (const row of rows) {
        const values = headers.map((h) => {
          const v = row[h];
          const str = v === null || v === undefined ? "" : String(v);
          const escaped = str.replace(/"/g, '""');
          return /[",\n]/.test(escaped) ? `"${escaped}"` : escaped;
        });
        lines.push(values.join(","));
      }
      return Buffer.from(lines.join("\n"), "utf8");
    }

    case "docx": {
      const lines = (content || "").split(/\r?\n/).filter(Boolean);
      const doc = new Document({
        sections: [
          {
            properties: {},
            children: (lines.length ? lines : ["Generated by Nexus"]).map(
              (line) => new Paragraph({ children: [new TextRun(line)] })
            ),
          },
        ],
      });
      return Buffer.from(await Packer.toBuffer(doc));
    }

    case "xlsx": {
      const workbook = new ExcelJS.Workbook();
      const sheet = workbook.addWorksheet("Sheet1");
      const rows = normalizeRows(jsonData !== undefined ? jsonData : content ? [{ content }] : []);
      if (rows.length > 0) {
        const headers = Array.from(new Set(rows.flatMap((r) => Object.keys(r))));
        sheet.addRow(headers);
        for (const row of rows) {
          sheet.addRow(headers.map((h) => row[h] ?? ""));
        }
      } else {
        sheet.addRow(["content"]);
        sheet.addRow([content || "Generated by Nexus"]);
      }
      return Buffer.from(await workbook.xlsx.writeBuffer());
    }

    case "pdf": {
      const pdf = await PDFDocument.create();
      const page = pdf.addPage([595, 842]);
      const font = await pdf.embedFont(StandardFonts.Helvetica);
      const text = normalizePdfText(content || "Generated by Nexus");
      const lines = text.split(/\r?\n/);
      let y = 800;
      for (const line of lines) {
        page.drawText(line, { x: 50, y, size: 12, font, color: rgb(0.08, 0.12, 0.22) });
        y -= 18;
        if (y < 40) break;
      }
      return Buffer.from(await pdf.save());
    }

    case "png": {
      const w = Math.max(FILE_IMAGE_MIN_DIMENSION, Math.min(FILE_IMAGE_MAX_DIMENSION, Math.floor(width || FILE_IMAGE_DEFAULT_WIDTH)));
      const h = Math.max(FILE_IMAGE_MIN_DIMENSION, Math.min(FILE_IMAGE_MAX_DIMENSION, Math.floor(height || FILE_IMAGE_DEFAULT_HEIGHT)));
      const image = new PNG({ width: w, height: h });
      for (let y = 0; y < h; y++) {
        for (let x = 0; x < w; x++) {
          const idx = (w * y + x) << 2;
          image.data[idx] = 12;
          image.data[idx + 1] = 27;
          image.data[idx + 2] = 48;
          image.data[idx + 3] = 255;
        }
      }
      return PNG.sync.write(image);
    }

    case "jpg": {
      const w = Math.max(FILE_IMAGE_MIN_DIMENSION, Math.min(FILE_IMAGE_MAX_DIMENSION, Math.floor(width || FILE_IMAGE_DEFAULT_WIDTH)));
      const h = Math.max(FILE_IMAGE_MIN_DIMENSION, Math.min(FILE_IMAGE_MAX_DIMENSION, Math.floor(height || FILE_IMAGE_DEFAULT_HEIGHT)));
      const data = Buffer.alloc(w * h * 4);
      for (let i = 0; i < data.length; i += 4) {
        data[i] = 12;
        data[i + 1] = 27;
        data[i + 2] = 48;
        data[i + 3] = 255;
      }
      return Buffer.from(jpeg.encode({ data, width: w, height: h }, 90).data);
    }

    default:
      throw new Error(`Unsupported file format: ${format}`);
  }
}

export function isFileTool(name: string): boolean {
  return resolveFileToolName(name) === FILE_TOOL_NAMES.GENERATE;
}

export async function executeBuiltinFileTool(
  name: string,
  args: Record<string, unknown>,
  context: { threadId?: string } = {}
): Promise<unknown> {
  const resolvedName = resolveFileToolName(name);
  if (resolvedName !== FILE_TOOL_NAMES.GENERATE) {
    throw new Error(`Unknown file tool: ${name}`);
  }

  const threadId = context.threadId;
  if (!threadId) {
    throw new Error("file_generate requires an active thread context.");
  }

  const rawFilename = typeof args.filename === "string" ? args.filename : "generated-file";
  const format = typeof args.format === "string" ? args.format.toLowerCase() : "";
  const content = typeof args.content === "string" ? args.content : "";
  const jsonData = args.jsonData;
  const width = typeof args.width === "number" ? args.width : 1024;
  const height = typeof args.height === "number" ? args.height : 576;

  if (!MIME_BY_FORMAT[format]) {
    throw new Error("Invalid format. Supported formats: txt, md, csv, json, docx, xlsx, pdf, png, jpg.");
  }

  const cleanName = sanitizeFilename(rawFilename);
  const expectedExt = `.${format}`;
  const finalFilename = cleanName.toLowerCase().endsWith(expectedExt)
    ? cleanName
    : `${cleanName}${expectedExt}`;

  const bytes = await generateBytes(format, content, jsonData, width, height);

  const threadDir = path.join(ATTACHMENTS_ROOT, threadId);
  fs.mkdirSync(threadDir, { recursive: true });

  const fileId = crypto.randomUUID();
  const storedName = `${fileId}${path.extname(finalFilename)}`;
  const fullPath = path.join(threadDir, storedName);
  fs.writeFileSync(fullPath, bytes);

  const attachment: AttachmentMeta = {
    id: fileId,
    filename: finalFilename,
    mimeType: MIME_BY_FORMAT[format],
    sizeBytes: bytes.length,
    storagePath: `${threadId}/${storedName}`,
  };

  return {
    status: "created",
    format,
    filename: finalFilename,
    sizeBytes: bytes.length,
    attachments: [attachment],
  };
}

// ── BaseTool class wrapper ────────────────────────────────────

export class FileTools extends BaseTool {
  readonly name = "file";
  readonly toolNamePrefix = "builtin.file_";
  readonly tools = BUILTIN_FILE_TOOLS;
  readonly toolsRequiringApproval = [...FILE_TOOLS_REQUIRING_APPROVAL];

  async execute(toolName: string, args: Record<string, unknown>, context: ToolExecutionContext): Promise<unknown> {
    return executeBuiltinFileTool(toolName, args, { threadId: context.threadId });
  }
}

export const fileTools = new FileTools();
